/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FormDialog: typeof import('./src/components/form-dialog.vue')['default']
    ResourceList: typeof import('./src/components/resource-list.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAction: typeof import('@veltra/desktop')['UAction']
    UActionGroup: typeof import('@veltra/desktop')['UActionGroup']
    UButton: typeof import('@veltra/desktop')['UButton']
    UCheckbox: typeof import('@veltra/desktop')['UCheckbox']
    UDialog: typeof import('@veltra/desktop')['UDialog']
    UDualNav: typeof import('@veltra/desktop')['UDualNav']
    UEmpty: typeof import('@veltra/desktop')['UEmpty']
    UForm: typeof import('@veltra/desktop')['UForm']
    UFormItem: typeof import('@veltra/desktop')['UFormItem']
    UInput: typeof import('@veltra/desktop')['UInput']
    UMultiSelect: typeof import('@veltra/desktop')['UMultiSelect']
    UNav: typeof import('@veltra/desktop')['UNav']
    UNumberInput: typeof import('@veltra/desktop')['UNumberInput']
    UPaginator: typeof import('@veltra/desktop')['UPaginator']
    UPasswordInput: typeof import('@veltra/desktop')['UPasswordInput']
    USelect: typeof import('@veltra/desktop')['USelect']
    USwitch: typeof import('@veltra/desktop')['USwitch']
    UTable: typeof import('@veltra/desktop')['UTable']
    UTextarea: typeof import('@veltra/desktop')['UTextarea']
    UTree: typeof import('@veltra/desktop')['UTree']
  }
}
