// Code generated by ent, DO NOT EDIT.

package model

import (
	"minidevops/internal/model/project"
	"minidevops/internal/model/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescBranch is the schema descriptor for branch field.
	projectDescBranch := projectFields[2].Descriptor()
	// project.DefaultBranch holds the default value on creation for the branch field.
	project.DefaultBranch = projectDescBranch.Default.(string)
}
