/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MDialog: typeof import('@/components')['MDialog']
    MPageTable: typeof import('@/components')['MPageTable']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAction: typeof import('ultra-ui')['UAction']
    UActionGroup: typeof import('ultra-ui')['UActionGroup']
    UButton: typeof import('ultra-ui')['UButton']
    UDialog: typeof import('ultra-ui')['UDialog']
    UForm: typeof import('ultra-ui')['UForm']
    UInput: typeof import('ultra-ui')['UInput']
    UPaginator: typeof import('ultra-ui')['UPaginator']
    UPasswordInput: typeof import('ultra-ui')['UPasswordInput']
    UTable: typeof import('ultra-ui')['UTable']
  }
}
