/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BuildLogViewer: typeof import('./src/components/build-log-viewer/build-log-viewer.vue')['default']
    FormDialog: typeof import('./src/components/form-dialog/form-dialog.vue')['default']
    NotificationBell: typeof import('./src/components/notification-bell/notification-bell.vue')['default']
    ProTable: typeof import('./src/components/pro-table/pro-table.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAction: typeof import('@veltra/desktop')['UAction']
    UActionGroup: typeof import('@veltra/desktop')['UActionGroup']
    UBadge: typeof import('@veltra/desktop')['UBadge']
    UButton: typeof import('@veltra/desktop')['UButton']
    UCard: typeof import('@veltra/desktop')['UCard']
    UCardContent: typeof import('@veltra/desktop')['UCardContent']
    UCardHeader: typeof import('@veltra/desktop')['UCardHeader']
    UCheckbox: typeof import('@veltra/desktop')['UCheckbox']
    UCodeEditor: typeof import('@veltra/desktop')['UCodeEditor']
    UDialog: typeof import('@veltra/desktop')['UDialog']
    UDropdown: typeof import('@veltra/desktop')['UDropdown']
    UEmpty: typeof import('@veltra/desktop')['UEmpty']
    UFilePicker: typeof import('@veltra/desktop')['UFilePicker']
    UForm: typeof import('@veltra/desktop')['UForm']
    UFormItem: typeof import('@veltra/desktop')['UFormItem']
    UInput: typeof import('@veltra/desktop')['UInput']
    UMultiSelect: typeof import('@veltra/desktop')['UMultiSelect']
    UNav: typeof import('@veltra/desktop')['UNav']
    UNumberInput: typeof import('@veltra/desktop')['UNumberInput']
    UPaginator: typeof import('@veltra/desktop')['UPaginator']
    UPasswordInput: typeof import('@veltra/desktop')['UPasswordInput']
    UScroll: typeof import('@veltra/desktop')['UScroll']
    USelect: typeof import('@veltra/desktop')['USelect']
    USwitch: typeof import('@veltra/desktop')['USwitch']
    UTable: typeof import('@veltra/desktop')['UTable']
    UTabs: typeof import('@veltra/desktop')['UTabs']
    UTag: typeof import('@veltra/desktop')['UTag']
    UTextarea: typeof import('@veltra/desktop')['UTextarea']
    UTree: typeof import('@veltra/desktop')['UTree']
  }
}
